start-at-login = false

accordion-padding = 40

after-startup-command = [
    'layout h_tiles',
]

[mode.main.binding]

    # cmd-ctrl as common prefix for all aerospace commands
    # ctrl-alt is used for rectangle

    # navigate
    cmd-ctrl-h = 'focus left --boundaries all-monitors-outer-frame'
    cmd-ctrl-j = 'focus down --boundaries all-monitors-outer-frame'
    cmd-ctrl-k = 'focus up --boundaries all-monitors-outer-frame'
    cmd-ctrl-l = 'focus right --boundaries all-monitors-outer-frame'

    # move window
    cmd-ctrl-shift-h = 'move left'
    cmd-ctrl-shift-j = 'move down'
    cmd-ctrl-shift-k = 'move up'
    cmd-ctrl-shift-l = 'move right'

    cmd-ctrl-shift-y = 'join-with left'
    cmd-ctrl-shift-u = 'join-with down'
    cmd-ctrl-shift-i = 'join-with up'
    cmd-ctrl-shift-o = 'join-with right'

    # swap (since 0.19)
    cmd-ctrl-shift-n = 'swap left'
    cmd-ctrl-shift-m = 'swap down'
    cmd-ctrl-shift-comma = 'swap up'
    cmd-ctrl-shift-period = 'swap right'

    # resize
    cmd-ctrl-minus = 'resize smart -200'
    cmd-ctrl-equal = 'resize smart +200'
    cmd-ctrl-shift-minus = 'resize smart-opposite -50'
    cmd-ctrl-shift-equal = 'resize smart-opposite +50'
    cmd-ctrl-enter = 'fullscreen'
    cmd-ctrl-slash = 'layout accordion tiles'
    cmd-ctrl-c = 'layout floating tiling'

    # workspace2
    cmd-ctrl-1 = 'workspace 1'
    cmd-ctrl-2 = 'workspace 2'

    cmd-ctrl-leftSquareBracket = 'workspace --wrap-around prev'
    cmd-ctrl-rightSquareBracket = 'workspace --wrap-around next'

    cmd-ctrl-shift-leftSquareBracket = 'move-node-to-workspace --focus-follows-window --wrap-around prev'
    cmd-ctrl-shift-rightSquareBracket = 'move-node-to-workspace --focus-follows-window --wrap-around next'
